### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by ric2016** [BlasiusSecundus/branch_export#3] opened 2018-03-26 17:48 UTC
The current version of the module causes javascript errors:
"ReferenceError: I18N is not defined" in "branch_export.js:282:5"

This negatively impacts other custom modules (that's how we came across this error, as discussed here:
https://www.webtrees.net/index.php/en/forum/4-customising/31605-solved-gov4webtrees-webtrees-module/66975)

Tested with 
webtrees: 1.7.9
php: 5.6.x and 7.2.2
branch_export: current master

**Comment by BlasiusSecundus** [comment] 2018-03-31 19:23
Thank you for letting me know this issue.
(Update: I think I found the real cause, see below)

**Comment by BlasiusSecundus** [comment] 2018-03-31 20:44
Meanwhile, I think I was able to reproduce the issue and found the definitive cause. If the user was not on the module’s page, the main JS files was still loaded (unnecessarily), but translate.js was not. This is now fixed and the unnecessary JS code is no longer loaded.

**Comment by BlasiusSecundus** [comment] 2018-04-08 06:56
I did some more testing, and I think the issue is fixed, ready for merging and closing the issue. Could you please test the fix/I18N branch, to double check it works correctly? Thanks.

**Comment by ric2016** [comment] 2018-04-08 12:03
I can confirm that the error no longer occurs when using the fix/I18N branch. Thanks!

**Comment by BlasiusSecundus** [comment] 2018-04-09 17:42
OK, thank you for the confirmation, fix merged into dev and master.

**Closed as completed by BlasiusSecundus** 2018-04-09 17:42 UTC
Labels: bug
